export const ACTIONS = {
	USER: {
		AUTH   : "AUTH",
		LOGOUT : "LOGOUT",
		LOGIN: {
			RQ: "LOGIN_RQ",
			SC: "LOGIN_SC",
			FL: "LOGIN_FL"
		},
		REGISTER: {
			RQ: "REGISTER_RQ",
			SC: "REGISTER_SC",
			FL: "REGISTER_FL"
		}
	},
	ONE_TEAM: {
		GET: {
			RQ: "ONE_TEAM_GET_RQ",
			SC: "ONE_TEAM_GET_SC",
			FL: "ONE_TEAM_GET_FL"
		},
		UPDATE_NAME: {
			RQ: "UPDATE_NAME_RQ",
			SC: "UPDATE_NAME_SC",
			FL: "UPDATE_NAME_FL"
		}
	},
	TEAM: {
		MESSAGE: "MESSAGE",
		DROP: {
			RQ: "TEAM_DROP_RQ",
			SC: "TEAM_DROP_SC",
			FL: "TEAM_DROP_FL"
		},
		CREATE: {
			RQ: "TEAM_CREATE_RQ",
			SC: "TEAM_CREATE_SC",
			FL: "TEAM_CREATE_FL"
		},
		GET: {
			RQ: "TEAM_GET_RQ",
			SC: "TEAM_GET_SC",
			FL: "TEAM_GET_FL"
		},
		USER_TEST: {
			RQ: "USER_TEST_RQ",
			SC: "USER_TEST_SC",
			FL: "USER_TEST_FL"
		}
	},
	HISTORY: {
		GET_ALL: {
			RQ: "HISTORY_GET_RQ",
			SC: "HISTORY_GET_SC",
			FL: "HISTORY_GET_FL"
		},
	},
	TASK: {
		GET: {
			RQ: "TASK_GET_RQ",
			SC: "TASK_GET_SC",
			FL: "TASK_GET_FL"
		},
		ADD: {
			RQ: "TASK_ADD_RQ",
			SC: "TASK_ADD_SC",
			FL: "TASK_ADD_FL"
		},
		REMOVE: {
			RQ: "TASK_REMOVE_RQ",
			SC: "TASK_REMOVE_SC",
			FL: "TASK_REMOVE_FL"
		},
		CHANGE: {
			RQ: "TASK_CHANGE_RQ",
			SC: "TASK_CHANGE_SC",
			FL: "TASK_CHANGE_FL"
		},
		REMOVE_MESSAGE: {
			RQ: "TASK_REMOVE_MESSAGE_RQ",
			SC: "TASK_REMOVE_MESSAGE_SC",
			FL: "TASK_REMOVE_MESSAGE_FL"
		}
	},
	BOARD: {
		MESSAGE: "BOARD_MESSAGE",
		GET_ALL: {
			RQ: "BOARD_GET_RQ",
			SC: "BOARD_GET_SC",
			FL: "BOARD_GET_FL"
		},
		CREATE_LIST: {
			RQ: "CREATE_LIST_RQ",
			SC: "CREATE_LIST_SC",
			FL: "CREATE_LIST_FL"
		},
		DROP_LIST: {
			RQ: "DROP_LIST_RQ",
			SC: "DROP_LIST_SC",
			FL: "DROP_LIST_FL"
		},
		DROP : {
			RQ: "BOARD_DROP_RQ",
			SC: "BOARD_DROP_SC",
			FL: "BOARD_DROP_FL"
		},
		CREATE: {
			RQ: "BOARD_CREATE_RQ",
			SC: "BOARD_CREATE_SC",
			FL: "BOARD_CREATE_FL"
		}
	}
};